// @generated by satay. Do not edit by hand.

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct ErrorBody {
    #[cfg_attr(
        feature = "serde",
        serde(default, skip_serializing_if = "Option::is_none")
    )]
    pub code: Option<String>,
    pub message: String,
}
#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct UpdateUserRequest {
    #[cfg_attr(
        feature = "serde",
        serde(default, skip_serializing_if = "Option::is_none")
    )]
    pub age: Option<i32>,
    pub name: String,
}
#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct User {
    #[cfg_attr(
        feature = "serde",
        serde(default, skip_serializing_if = "Option::is_none")
    )]
    pub age: Option<i32>,
    pub id: String,
    pub name: String,
    pub status: UserStatus,
    #[cfg_attr(
        feature = "serde",
        serde(default, skip_serializing_if = "Option::is_none")
    )]
    pub tags: Option<Vec<String>>,
}
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub enum UserStatus {
    #[cfg_attr(feature = "serde", serde(rename = "active"))]
    Active,
    #[cfg_attr(feature = "serde", serde(rename = "suspended"))]
    Suspended,
}
impl UserStatus {
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::Active => "active",
            Self::Suspended => "suspended",
        }
    }
}
impl AsRef<str> for UserStatus {
    fn as_ref(&self) -> &str {
        self.as_str()
    }
}
impl std::fmt::Display for UserStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}
#[derive(Debug, Clone, PartialEq)]
pub struct GetUserInput {
    pub user_id: String,
    pub include_details: Option<bool>,
}
#[derive(Debug, Clone, PartialEq)]
pub enum GetUserResponse {
    Ok(User),
    NotFound(ErrorBody),
    UnexpectedStatus(http::StatusCode, Vec<u8>),
}
pub fn get_user_parts(
    input: GetUserInput,
) -> Result<satay_runtime::RequestParts<()>, satay_runtime::Error> {
    let mut uri = String::with_capacity(15);
    uri.push_str("/users/");
    satay_runtime::append_path_segment(&mut uri, input.user_id.as_str());
    let mut first_query = true;
    if let Some(value) = &input.include_details {
        satay_runtime::append_query_pair(
            &mut uri,
            &mut first_query,
            "includeDetails",
            &value.to_string(),
        );
    }
    let headers = http::HeaderMap::new();
    Ok(satay_runtime::RequestParts {
        method: http::Method::GET,
        uri,
        headers,
        body: (),
    })
}
#[cfg(feature = "json")]
pub fn encode_get_user(
    input: GetUserInput,
) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
    let parts = get_user_parts(input)?;
    satay_runtime::into_empty_request(parts)
}
#[cfg(feature = "json")]
pub fn decode_get_user_response(
    response: http::Response<Vec<u8>>,
) -> Result<GetUserResponse, satay_runtime::Error> {
    let status = response.status();
    match status.as_u16() {
        200 => {
            let body = response.into_body();
            let value = satay_runtime::from_json_slice::<User>(&body)?;
            Ok(GetUserResponse::Ok(value))
        }
        404 => {
            let body = response.into_body();
            let value = satay_runtime::from_json_slice::<ErrorBody>(&body)?;
            Ok(GetUserResponse::NotFound(value))
        }
        _ => {
            let body = response.into_body();
            Ok(GetUserResponse::UnexpectedStatus(status, body))
        }
    }
}
#[derive(Debug, Clone, PartialEq)]
pub struct UpdateUserInput {
    pub user_id: String,
    pub notify: Option<bool>,
    pub body: Option<UpdateUserRequest>,
}
#[derive(Debug, Clone, PartialEq)]
pub enum UpdateUserResponse {
    Ok(User),
    BadRequest(ErrorBody),
    UnexpectedStatus(http::StatusCode, Vec<u8>),
}
pub fn update_user_parts(
    input: UpdateUserInput,
) -> Result<
    satay_runtime::RequestParts<Option<UpdateUserRequest>>,
    satay_runtime::Error,
> {
    let mut uri = String::with_capacity(15);
    uri.push_str("/users/");
    satay_runtime::append_path_segment(&mut uri, input.user_id.as_str());
    let mut first_query = true;
    if let Some(value) = &input.notify {
        satay_runtime::append_query_pair(
            &mut uri,
            &mut first_query,
            "notify",
            &value.to_string(),
        );
    }
    let mut headers = http::HeaderMap::new();
    if input.body.is_some() {
        headers
            .insert(
                http::header::CONTENT_TYPE,
                http::HeaderValue::from_static("application/vnd.satay.user+json"),
            );
    }
    Ok(satay_runtime::RequestParts {
        method: http::Method::PUT,
        uri,
        headers,
        body: input.body,
    })
}
#[cfg(feature = "json")]
pub fn encode_update_user(
    input: UpdateUserInput,
) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
    let parts = update_user_parts(input)?;
    satay_runtime::into_optional_json_request(parts)
}
#[cfg(feature = "json")]
pub fn decode_update_user_response(
    response: http::Response<Vec<u8>>,
) -> Result<UpdateUserResponse, satay_runtime::Error> {
    let status = response.status();
    match status.as_u16() {
        200 => {
            let body = response.into_body();
            let value = satay_runtime::from_json_slice::<User>(&body)?;
            Ok(UpdateUserResponse::Ok(value))
        }
        400 => {
            let body = response.into_body();
            let value = satay_runtime::from_json_slice::<ErrorBody>(&body)?;
            Ok(UpdateUserResponse::BadRequest(value))
        }
        _ => {
            let body = response.into_body();
            Ok(UpdateUserResponse::UnexpectedStatus(status, body))
        }
    }
}
