use std::fmt::Write as _;

use crate::error::Error;
use crate::ident::rust_string;
use crate::model::{
    Api, Component, ComponentKind, ConstrainedType, EnumVariant, Field, FloatLimit, IntegerLimit,
    Operation, Parameter, ParameterLocation, PathSegment, TypeRef, Validation, is_array_type,
};

pub(crate) fn render_api(api: &Api) -> Result<String, Error> {
    let mut raw = String::new();
    for component in &api.components {
        render_component(&mut raw, component);
        raw.push('\n');
    }
    for constrained_type in &api.constrained_types {
        render_constrained_type(&mut raw, constrained_type);
        raw.push('\n');
    }
    for operation in &api.operations {
        render_input(&mut raw, operation);
        raw.push('\n');
        render_response(&mut raw, operation);
        raw.push('\n');
        render_parts_function(&mut raw, operation);
        raw.push('\n');
        render_encode_function(&mut raw, operation);
        raw.push('\n');
        render_decode_function(&mut raw, operation);
        raw.push('\n');
    }

    let syntax = syn::parse_file(&raw).map_err(|source| Error::GeneratedInvalidRust {
        source,
        raw: raw.clone(),
    })?;

    let mut formatted = String::from("// @generated by satay. Do not edit by hand.\n\n");
    formatted.push_str(&prettyplease::unparse(&syntax));
    Ok(formatted)
}

fn render_component(out: &mut String, component: &Component) {
    match &component.kind {
        ComponentKind::Struct(fields) => render_struct(out, &component.rust_name, fields, true),
        ComponentKind::Enum(variants) => render_enum(out, &component.rust_name, variants),
        ComponentKind::Alias(ty) => {
            let _ = writeln!(
                out,
                "pub type {} = {};",
                component.rust_name,
                ty.rust_type()
            );
        }
        ComponentKind::Nutype(constrained_type) => render_constrained_type(out, constrained_type),
    }
}

fn render_constrained_type(out: &mut String, constrained_type: &ConstrainedType) {
    let _ = writeln!(out, "#[nutype::nutype(");
    render_validation(out, &constrained_type.validation);
    let _ = writeln!(
        out,
        "derive({}),",
        nutype_derives(&constrained_type.validation)
    );
    let _ = writeln!(
        out,
        "cfg_attr(feature = \"serde\", derive(Serialize, Deserialize)),"
    );
    let _ = writeln!(out, ")]");
    let _ = writeln!(
        out,
        "pub struct {}({});",
        constrained_type.rust_name,
        constrained_type.inner.rust_type()
    );
}

fn render_validation(out: &mut String, validation: &Validation) {
    match validation {
        Validation::String {
            min_length,
            max_length,
        } => {
            let mut validators = Vec::new();
            if let Some(min_length) = min_length {
                validators.push(format!("len_char_min = {min_length}"));
            }
            if let Some(max_length) = max_length {
                validators.push(format!("len_char_max = {max_length}"));
            }
            let _ = writeln!(out, "validate({}),", validators.join(", "));
        }
        Validation::Integer { minimum, maximum } => {
            let mut validators = Vec::new();
            if let Some(minimum) = minimum {
                validators.push(integer_limit_validator(
                    "greater",
                    "greater_or_equal",
                    *minimum,
                ));
            }
            if let Some(maximum) = maximum {
                validators.push(integer_limit_validator("less", "less_or_equal", *maximum));
            }
            let _ = writeln!(out, "validate({}),", validators.join(", "));
        }
        Validation::Number { minimum, maximum } => {
            let mut validators = vec!["finite".to_owned()];
            if let Some(minimum) = minimum {
                validators.push(float_limit_validator(
                    "greater",
                    "greater_or_equal",
                    *minimum,
                ));
            }
            if let Some(maximum) = maximum {
                validators.push(float_limit_validator("less", "less_or_equal", *maximum));
            }
            let _ = writeln!(out, "validate({}),", validators.join(", "));
        }
        Validation::Array {
            min_items,
            max_items,
        } => {
            let predicate = array_predicate(*min_items, *max_items);
            let _ = writeln!(out, "validate(predicate = {predicate}),");
        }
    }
}

fn nutype_derives(validation: &Validation) -> &'static str {
    match validation {
        Validation::String { .. } => {
            "Debug, Clone, PartialEq, Eq, PartialOrd, Ord, AsRef, Deref, TryFrom, Into, Display"
        }
        Validation::Integer { .. } => {
            "Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, AsRef, Deref, TryFrom, Into, Display"
        }
        Validation::Number { .. } => {
            "Debug, Clone, Copy, PartialEq, PartialOrd, AsRef, Deref, TryFrom, Into, Display"
        }
        Validation::Array { .. } => "Debug, Clone, PartialEq, AsRef, Deref, TryFrom, Into",
    }
}

fn integer_limit_validator(
    exclusive_name: &str,
    inclusive_name: &str,
    limit: IntegerLimit,
) -> String {
    if limit.exclusive {
        format!("{exclusive_name} = {}", limit.value)
    } else {
        format!("{inclusive_name} = {}", limit.value)
    }
}

fn float_limit_validator(exclusive_name: &str, inclusive_name: &str, limit: FloatLimit) -> String {
    let value = rust_float(limit.value);
    if limit.exclusive {
        format!("{exclusive_name} = {value}")
    } else {
        format!("{inclusive_name} = {value}")
    }
}

fn array_predicate(min_items: Option<u64>, max_items: Option<u64>) -> String {
    match (min_items, max_items) {
        (Some(min_items), Some(max_items)) => {
            format!("|items| items.len() >= {min_items} && items.len() <= {max_items}")
        }
        (Some(min_items), None) => format!("|items| items.len() >= {min_items}"),
        (None, Some(max_items)) => format!("|items| items.len() <= {max_items}"),
        (None, None) => unreachable!("array validation requires at least one bound"),
    }
}

fn rust_float(value: f64) -> String {
    let rendered = value.to_string();
    if rendered.contains('.') || rendered.contains('e') || rendered.contains('E') {
        rendered
    } else {
        format!("{rendered}.0")
    }
}

fn render_struct(out: &mut String, name: &str, fields: &[Field], serde: bool) {
    let _ = writeln!(out, "#[derive(Debug, Clone, PartialEq)]");
    if serde {
        let _ = writeln!(
            out,
            "#[cfg_attr(feature = \"serde\", derive(serde::Serialize, serde::Deserialize))]"
        );
    }
    let _ = writeln!(out, "pub struct {name} {{");
    for field in fields {
        if serde {
            let mut serde_attrs = Vec::new();
            if field.rust_name != field.wire_name {
                serde_attrs.push(format!("rename = {}", rust_string(&field.wire_name)));
            }
            if !field.required {
                serde_attrs.push("default".to_owned());
                serde_attrs.push("skip_serializing_if = \"Option::is_none\"".to_owned());
            }
            if !serde_attrs.is_empty() {
                let _ = writeln!(
                    out,
                    "#[cfg_attr(feature = \"serde\", serde({}))]",
                    serde_attrs.join(", ")
                );
            }
        }
        let _ = writeln!(
            out,
            "pub {}: {},",
            field.rust_name,
            field.ty.rust_field_type(field.required)
        );
    }
    let _ = writeln!(out, "}}");
}

fn render_enum(out: &mut String, name: &str, variants: &[EnumVariant]) {
    let _ = writeln!(out, "#[derive(Debug, Clone, PartialEq, Eq)]");
    let _ = writeln!(
        out,
        "#[cfg_attr(feature = \"serde\", derive(serde::Serialize, serde::Deserialize))]"
    );
    let _ = writeln!(out, "pub enum {name} {{");
    for variant in variants {
        if variant.rust_name != variant.wire_name {
            let _ = writeln!(
                out,
                "#[cfg_attr(feature = \"serde\", serde(rename = {}))]",
                rust_string(&variant.wire_name)
            );
        }
        let _ = writeln!(out, "{},", variant.rust_name);
    }
    let _ = writeln!(out, "}}");
    let _ = writeln!(out, "impl {name} {{");
    let _ = writeln!(out, "pub const fn as_str(&self) -> &'static str {{");
    let _ = writeln!(out, "match self {{");
    for variant in variants {
        let _ = writeln!(
            out,
            "Self::{} => {},",
            variant.rust_name,
            rust_string(&variant.wire_name)
        );
    }
    let _ = writeln!(out, "}}");
    let _ = writeln!(out, "}}");
    let _ = writeln!(out, "}}");
    let _ = writeln!(out, "impl AsRef<str> for {name} {{");
    let _ = writeln!(out, "fn as_ref(&self) -> &str {{ self.as_str() }}");
    let _ = writeln!(out, "}}");
    let _ = writeln!(out, "impl std::fmt::Display for {name} {{");
    let _ = writeln!(
        out,
        "fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {{ f.write_str(self.as_str()) }}"
    );
    let _ = writeln!(out, "}}");
}

fn render_input(out: &mut String, operation: &Operation) {
    let mut fields = operation.parameters.iter().map(|parameter| Field {
        wire_name: parameter.wire_name.clone(),
        rust_name: parameter.rust_name.clone(),
        ty: parameter.ty.clone(),
        required: parameter.required,
    });
    let mut input_fields = Vec::with_capacity(
        operation.parameters.len() + usize::from(operation.request_body.is_some()),
    );
    input_fields.extend(fields.by_ref());
    if let Some(body) = &operation.request_body {
        input_fields.push(Field {
            wire_name: body.field_name.clone(),
            rust_name: body.field_name.clone(),
            ty: body.ty.clone(),
            required: body.required,
        });
    }

    render_struct(out, &operation.input_name, &input_fields, false);
}

fn render_response(out: &mut String, operation: &Operation) {
    let _ = writeln!(out, "#[derive(Debug, Clone, PartialEq)]");
    let _ = writeln!(out, "pub enum {} {{", operation.response_name);
    for response in &operation.responses {
        match &response.body {
            Some(body) => {
                let _ = writeln!(out, "{}({}),", response.variant_name, body.rust_type());
            }
            None => {
                let _ = writeln!(out, "{},", response.variant_name);
            }
        }
    }
    let _ = writeln!(out, "UnexpectedStatus(http::StatusCode, Vec<u8>),");
    let _ = writeln!(out, "}}");
}

fn render_parts_function(out: &mut String, operation: &Operation) {
    let body_type = operation.request_body.as_ref().map_or_else(
        || "()".to_owned(),
        |body| body.ty.rust_field_type(body.required),
    );
    let parts_fn = format!("{}_parts", operation.fn_name);
    let input_name = if operation_uses_input(operation) {
        "input"
    } else {
        "_input"
    };

    let _ = writeln!(
        out,
        "pub fn {parts_fn}({input_name}: {}) -> Result<satay_runtime::RequestParts<{body_type}>, satay_runtime::Error> {{",
        operation.input_name
    );
    let _ = writeln!(
        out,
        "let mut uri = String::with_capacity({});",
        operation.path.len()
    );
    render_path(out, operation);
    render_query(out, operation);
    match &operation.request_body {
        Some(body) => {
            let _ = writeln!(out, "let mut headers = http::HeaderMap::new();");
            if body.required {
                let _ = writeln!(
                    out,
                    "headers.insert(http::header::CONTENT_TYPE, http::HeaderValue::from_static({}));",
                    rust_string(&body.content_type)
                );
            } else {
                let _ = writeln!(out, "if input.{}.is_some() {{", body.field_name);
                let _ = writeln!(
                    out,
                    "headers.insert(http::header::CONTENT_TYPE, http::HeaderValue::from_static({}));",
                    rust_string(&body.content_type)
                );
                let _ = writeln!(out, "}}");
            }
        }
        None => {
            let _ = writeln!(out, "let headers = http::HeaderMap::new();");
        }
    }
    let _ = writeln!(out, "Ok(satay_runtime::RequestParts {{");
    let _ = writeln!(
        out,
        "method: http::Method::{},",
        operation.method.rust_const()
    );
    let _ = writeln!(out, "uri,");
    let _ = writeln!(out, "headers,");
    match &operation.request_body {
        Some(body) => {
            let _ = writeln!(out, "body: input.{},", body.field_name);
        }
        None => {
            let _ = writeln!(out, "body: (),");
        }
    }
    let _ = writeln!(out, "}})");
    let _ = writeln!(out, "}}");
}

fn render_path(out: &mut String, operation: &Operation) {
    for segment in &operation.path_segments {
        match segment {
            PathSegment::Literal(literal) if !literal.is_empty() => {
                let _ = writeln!(out, "uri.push_str({});", rust_string(literal));
            }
            PathSegment::Literal(_) => {}
            PathSegment::Parameter(name) => {
                let parameter = operation
                    .parameters
                    .iter()
                    .find(|parameter| {
                        parameter.location == ParameterLocation::Path
                            && parameter.wire_name == *name
                    })
                    .expect("path parameters validated before render");
                let expr = value_expr(&format!("input.{}", parameter.rust_name), &parameter.ty);
                let _ = writeln!(out, "satay_runtime::append_path_segment(&mut uri, {expr});");
            }
        }
    }
}

fn render_query(out: &mut String, operation: &Operation) {
    let query_parameters = operation
        .parameters
        .iter()
        .filter(|parameter| parameter.location == ParameterLocation::Query)
        .collect::<Vec<_>>();
    if query_parameters.is_empty() {
        return;
    }

    let _ = writeln!(out, "let mut first_query = true;");
    for parameter in query_parameters {
        render_query_parameter(out, parameter);
    }
}

fn render_query_parameter(out: &mut String, parameter: &Parameter) {
    if let Some(item) = array_item_type(parameter.ty.non_nullable()) {
        if parameter.required {
            let values =
                array_values_expr(&format!("input.{}", parameter.rust_name), &parameter.ty);
            let _ = writeln!(out, "for value in {values} {{");
            let expr = value_expr("value", item);
            let _ = writeln!(
                out,
                "satay_runtime::append_query_pair(&mut uri, &mut first_query, {}, {expr});",
                rust_string(&parameter.wire_name)
            );
            let _ = writeln!(out, "}}");
        } else {
            let _ = writeln!(
                out,
                "if let Some(values) = &input.{} {{",
                parameter.rust_name
            );
            let values = array_values_expr("values", &parameter.ty);
            let _ = writeln!(out, "for value in {values} {{");
            let expr = value_expr("value", item);
            let _ = writeln!(
                out,
                "satay_runtime::append_query_pair(&mut uri, &mut first_query, {}, {expr});",
                rust_string(&parameter.wire_name)
            );
            let _ = writeln!(out, "}}");
            let _ = writeln!(out, "}}");
        }
        return;
    }

    if parameter.required {
        let expr = value_expr(&format!("input.{}", parameter.rust_name), &parameter.ty);
        let _ = writeln!(
            out,
            "satay_runtime::append_query_pair(&mut uri, &mut first_query, {}, {expr});",
            rust_string(&parameter.wire_name)
        );
    } else {
        let _ = writeln!(
            out,
            "if let Some(value) = &input.{} {{",
            parameter.rust_name
        );
        let expr = value_expr("value", &parameter.ty);
        let _ = writeln!(
            out,
            "satay_runtime::append_query_pair(&mut uri, &mut first_query, {}, {expr});",
            rust_string(&parameter.wire_name)
        );
        let _ = writeln!(out, "}}");
    }
}

fn array_item_type(ty: &TypeRef) -> Option<&TypeRef> {
    match ty {
        TypeRef::Array(item) => Some(item),
        TypeRef::Constrained { inner, .. } => array_item_type(inner.non_nullable()),
        _ => None,
    }
}

fn array_values_expr(base: &str, ty: &TypeRef) -> String {
    match ty.non_nullable() {
        TypeRef::Array(_) => format!("&{base}"),
        TypeRef::Constrained { inner, .. } if is_array_type(inner.non_nullable()) => {
            format!("{base}.as_ref()")
        }
        _ => unreachable!("array values are only rendered for array types"),
    }
}

fn render_encode_function(out: &mut String, operation: &Operation) {
    let parts_fn = format!("{}_parts", operation.fn_name);
    let encode_fn = format!("encode_{}", operation.fn_name);
    let _ = writeln!(out, "#[cfg(feature = \"json\")]");
    let _ = writeln!(
        out,
        "pub fn {encode_fn}(input: {}) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {{",
        operation.input_name
    );
    let _ = writeln!(out, "let parts = {parts_fn}(input)?;");
    match &operation.request_body {
        Some(body) if body.required => {
            let _ = writeln!(out, "satay_runtime::into_json_request(parts)");
        }
        Some(_) => {
            let _ = writeln!(out, "satay_runtime::into_optional_json_request(parts)");
        }
        None => {
            let _ = writeln!(out, "satay_runtime::into_empty_request(parts)");
        }
    }
    let _ = writeln!(out, "}}");
}

fn render_decode_function(out: &mut String, operation: &Operation) {
    let decode_fn = format!("decode_{}_response", operation.fn_name);
    let _ = writeln!(out, "#[cfg(feature = \"json\")]");
    let _ = writeln!(
        out,
        "pub fn {decode_fn}(response: http::Response<Vec<u8>>) -> Result<{}, satay_runtime::Error> {{",
        operation.response_name
    );
    let _ = writeln!(out, "let status = response.status();");
    let _ = writeln!(out, "match status.as_u16() {{");
    for response in &operation.responses {
        let _ = writeln!(out, "{} => {{", response.status);
        match &response.body {
            Some(body) => {
                let _ = writeln!(out, "let body = response.into_body();");
                let _ = writeln!(
                    out,
                    "let value = satay_runtime::from_json_slice::<{}>(&body)?;",
                    body.rust_type()
                );
                let _ = writeln!(
                    out,
                    "Ok({}::{}(value))",
                    operation.response_name, response.variant_name
                );
            }
            None => {
                let _ = writeln!(
                    out,
                    "Ok({}::{})",
                    operation.response_name, response.variant_name
                );
            }
        }
        let _ = writeln!(out, "}}");
    }
    let _ = writeln!(out, "_ => {{");
    let _ = writeln!(out, "let body = response.into_body();");
    let _ = writeln!(
        out,
        "Ok({}::UnexpectedStatus(status, body))",
        operation.response_name
    );
    let _ = writeln!(out, "}}");
    let _ = writeln!(out, "}}");
    let _ = writeln!(out, "}}");
}

fn operation_uses_input(operation: &Operation) -> bool {
    !operation.parameters.is_empty() || operation.request_body.is_some()
}

fn value_expr(base: &str, ty: &TypeRef) -> String {
    match ty.non_nullable() {
        TypeRef::String => format!("{base}.as_str()"),
        TypeRef::Named(_) => format!("{base}.as_ref()"),
        TypeRef::Constrained { inner, .. } => constrained_value_expr(base, inner.non_nullable()),
        TypeRef::I32 | TypeRef::I64 | TypeRef::F32 | TypeRef::F64 | TypeRef::Bool => {
            format!("&{base}.to_string()")
        }
        TypeRef::Array(_) | TypeRef::Nullable(_) => unreachable!("arrays are handled by caller"),
    }
}

fn constrained_value_expr(base: &str, inner: &TypeRef) -> String {
    match inner {
        TypeRef::String | TypeRef::Named(_) => format!("{base}.as_ref()"),
        TypeRef::I32 | TypeRef::I64 | TypeRef::F32 | TypeRef::F64 | TypeRef::Bool => {
            format!("&{base}.to_string()")
        }
        TypeRef::Array(_) | TypeRef::Constrained { .. } | TypeRef::Nullable(_) => {
            unreachable!("arrays are handled by caller")
        }
    }
}
