use proc_macro2::{Literal, Span, TokenStream};
use quote::quote;
use std::collections::BTreeSet;
use syn::{Ident, Item, LitStr, parse_quote};

use crate::model::{
    Api, Component, ComponentKind, ConstrainedType, EnumVariant, Field, FloatLimit, IntegerLimit,
    Operation, Parameter, ParameterLocation, PathSegment, ResponseCase, TypeRef, Validation,
    is_array_type,
};

const PREAMBLE: &str = "\
//! @generated by satay. Do not edit by hand.

";

#[derive(Debug)]
pub struct GeneratedFile {
    pub relative_path: String,
    pub contents: String,
}

pub(crate) fn render_api(api: &Api) -> Vec<GeneratedFile> {
    tracing::info!(components = api.components.len(), operations = api.operations.len(), "rendering API");
    let mut files = Vec::new();

    let top_mod = render_top_mod(api);
    files.push(GeneratedFile {
        relative_path: "mod.rs".to_owned(),
        contents: format_file(top_mod),
    });

    if !api.components.is_empty() || !api.constrained_types.is_empty() {
        let types_file = render_types_file(api);
        files.push(GeneratedFile {
            relative_path: "types.rs".to_owned(),
            contents: format_file(types_file),
        });
    }

    for operation in &api.operations {
        let dir = &operation.fn_name;
        let endpoint_mod = render_endpoint_mod(operation);
        files.push(GeneratedFile {
            relative_path: format!("{dir}/mod.rs"),
            contents: format_file(endpoint_mod),
        });

        let parts_file = render_endpoint_parts_file(api, operation);
        files.push(GeneratedFile {
            relative_path: format!("{dir}/parts.rs"),
            contents: format_file(parts_file),
        });

        let json_file = render_endpoint_json_file(api, operation);
        files.push(GeneratedFile {
            relative_path: format!("{dir}/json.rs"),
            contents: format_file(json_file),
        });
    }

    tracing::info!(files = files.len(), "rendered API");
    files
}

fn format_file(file: syn::File) -> String {
    let code = prettyplease::unparse(&file);
    let code = add_blank_lines_between_items(&code);
    let mut formatted = String::with_capacity(PREAMBLE.len() + code.len());
    formatted.push_str(PREAMBLE);
    formatted.push_str(&code);
    formatted
}

fn add_blank_lines_between_items(code: &str) -> String {
    let mut result = String::with_capacity(code.len() + code.len() / 4);
    let mut lines = code.lines().peekable();
    while let Some(line) = lines.next() {
        result.push_str(line);
        result.push('\n');
        if (line == "}" || line.ends_with(" {}"))
            && let Some(next) = lines.peek()
            && (next.starts_with('#')
                || next.starts_with("pub ")
                || next.starts_with("impl ")
                || next.starts_with("use "))
        {
            result.push('\n');
        }
    }
    result
}

fn render_top_mod(api: &Api) -> syn::File {
    let mut items: Vec<syn::Item> = Vec::new();

    let has_types = !api.components.is_empty() || !api.constrained_types.is_empty();
    if has_types {
        items.push(parse_quote!(pub mod types;));
        items.push(parse_quote!(pub use types::*;));
    }

    for operation in &api.operations {
        let module = ident(&operation.fn_name);
        items.push(parse_quote!(pub mod #module;));
        items.push(parse_quote!(pub use #module::*;));
    }

    syn::File {
        shebang: None,
        attrs: vec![],
        items,
    }
}

fn render_types_file(api: &Api) -> syn::File {
    let mut items = Vec::new();
    for component in &api.components {
        render_component(component, &mut items);
    }
    for constrained_type in &api.constrained_types {
        items.push(Item::Struct(render_constrained_type(constrained_type)));
    }

    syn::File {
        shebang: None,
        attrs: vec![],
        items,
    }
}

fn render_endpoint_mod(_operation: &Operation) -> syn::File {
    syn::File {
        shebang: None,
        attrs: vec![],
        items: vec![
            parse_quote!(mod parts;),
            parse_quote!(#[cfg(feature = "json")] mod json;),
            parse_quote!(pub use parts::*;),
            parse_quote!(#[cfg(feature = "json")] pub use json::*;),
        ],
    }
}

fn render_endpoint_parts_file(api: &Api, operation: &Operation) -> syn::File {
    let mut items = Vec::new();
    let use_types = build_types_use(api, operation);
    items.push(Item::Use(use_types));
    items.push(Item::Struct(render_input(operation)));
    items.push(Item::Enum(render_response(operation)));
    items.push(Item::Fn(render_parts_function(operation)));

    syn::File {
        shebang: None,
        attrs: vec![],
        items,
    }
}

fn render_endpoint_json_file(api: &Api, operation: &Operation) -> syn::File {
    let mut items = Vec::new();
    let use_types = build_types_use(api, operation);
    items.push(Item::Use(use_types));
    let input_name = ident(&operation.input_name);
    let response_name = ident(&operation.response_name);
    let parts_fn = ident(&format!("{}_parts", operation.fn_name));
    items.push(Item::Use(parse_quote!(use super::parts::{#input_name, #response_name, #parts_fn};)));
    items.push(Item::Fn(render_encode_function(operation)));
    items.push(Item::Fn(render_decode_function(operation)));

    syn::File {
        shebang: None,
        attrs: vec![],
        items,
    }
}

fn build_types_use(api: &Api, operation: &Operation) -> syn::ItemUse {
    let mut needed_names: Vec<Ident> = Vec::new();

    for param in &operation.parameters {
        collect_type_refs(&param.ty, &mut needed_names);
    }
    if let Some(body) = &operation.request_body {
        collect_type_refs(&body.ty, &mut needed_names);
    }
    for response in &operation.responses {
        if let Some(body) = &response.body {
            collect_type_refs(body, &mut needed_names);
        }
    }

    let mut all_names: Vec<Ident> = needed_names;
    if operation.request_body.is_some() || !operation.parameters.is_empty() {
        let input_ident = ident(&operation.input_name);
        if !all_names.iter().any(|n| n == &input_ident) {
            // Input type is defined locally, no need to import
        }
    }
    all_names.sort_by(|a, b| a.to_string().cmp(&b.to_string()));
    all_names.dedup();

    // Filter: only import names that are in the types module (components and constrained types)
    let type_names = api
        .components
        .iter()
        .map(|c| c.rust_name.clone())
        .chain(api.constrained_types.iter().map(|c| c.rust_name.clone()))
        .collect::<BTreeSet<String>>();

    let names = all_names
        .into_iter()
        .filter(|n| type_names.contains(&n.to_string()))
        .collect::<Vec<Ident>>();

    if names.is_empty() {
        return parse_quote!(use super::super::types;);
    }

    parse_quote!(use super::super::types::{#(#names),*};)
}

fn collect_type_refs(ty: &TypeRef, names: &mut Vec<Ident>) {
    match ty {
        TypeRef::Named(name) => {
            names.push(ident(name));
        }
        TypeRef::Constrained { rust_name, .. } => {
            names.push(ident(rust_name));
        }
        TypeRef::Array(inner) => collect_type_refs(inner, names),
        TypeRef::Nullable(inner) => collect_type_refs(inner, names),
        TypeRef::String | TypeRef::I32 | TypeRef::I64 | TypeRef::F32 | TypeRef::F64 | TypeRef::Bool => {}
    }
}

fn render_component(component: &Component, items: &mut Vec<syn::Item>) {
    match &component.kind {
        ComponentKind::Struct(fields) => {
            items.push(Item::Struct(render_struct(
                &component.rust_name,
                fields,
                true,
            )));
        }
        ComponentKind::Enum(variants) => items.extend(render_enum(&component.rust_name, variants)),
        ComponentKind::Alias(ty) => {
            let name = ident(&component.rust_name);
            let ty = rust_type(ty);
            items.push(parse_quote!(pub type #name = #ty;));
        }
        ComponentKind::Nutype(constrained_type) => {
            items.push(Item::Struct(render_constrained_type(constrained_type)));
        }
    }
}

fn render_constrained_type(constrained_type: &ConstrainedType) -> syn::ItemStruct {
    let name = ident(&constrained_type.rust_name);
    let inner = rust_type(&constrained_type.inner);
    let validation = render_validation(&constrained_type.validation);
    let derives = nutype_derives(&constrained_type.validation);

    parse_quote!(
        #[nutype::nutype(
            #validation,
            derive(#(#derives),*),
            cfg_attr(feature = "serde", derive(Serialize, Deserialize)),
        )]
        pub struct #name(#inner);
    )
}

fn render_validation(validation: &Validation) -> TokenStream {
    match validation {
        Validation::String {
            min_length,
            max_length,
            pattern,
        } => {
            let mut validators = Vec::new();
            if let Some(pattern) = pattern {
                let pattern = lit_str(pattern);
                validators.push(quote!(regex = #pattern));
            }
            if let Some(min_length) = min_length {
                let min_length = Literal::u64_unsuffixed(*min_length);
                validators.push(quote!(len_char_min = #min_length));
            }
            if let Some(max_length) = max_length {
                let max_length = Literal::u64_unsuffixed(*max_length);
                validators.push(quote!(len_char_max = #max_length));
            }
            quote!(validate(#(#validators),*))
        }
        Validation::Integer { minimum, maximum } => {
            let mut validators = Vec::new();
            if let Some(minimum) = minimum {
                validators.push(integer_limit_validator(
                    "greater",
                    "greater_or_equal",
                    *minimum,
                ));
            }
            if let Some(maximum) = maximum {
                validators.push(integer_limit_validator("less", "less_or_equal", *maximum));
            }
            quote!(validate(#(#validators),*))
        }
        Validation::Number { minimum, maximum } => {
            let mut validators = vec![quote!(finite)];
            if let Some(minimum) = minimum {
                validators.push(float_limit_validator(
                    "greater",
                    "greater_or_equal",
                    *minimum,
                ));
            }
            if let Some(maximum) = maximum {
                validators.push(float_limit_validator("less", "less_or_equal", *maximum));
            }
            quote!(validate(#(#validators),*))
        }
        Validation::Array {
            min_items,
            max_items,
        } => {
            let predicate = array_predicate(*min_items, *max_items);
            quote!(validate(#predicate))
        }
    }
}

fn nutype_derives(validation: &Validation) -> Vec<TokenStream> {
    let mut derives = vec![quote!(Debug), quote!(Clone)];

    match validation {
        Validation::String { .. } => {
            derives.extend([
                quote!(PartialEq),
                quote!(Eq),
                quote!(PartialOrd),
                quote!(Ord),
                quote!(AsRef),
                quote!(Deref),
                quote!(TryFrom),
                quote!(Into),
                quote!(Display),
            ]);
        }
        Validation::Integer { .. } => {
            derives.extend([
                quote!(Copy),
                quote!(PartialEq),
                quote!(Eq),
                quote!(PartialOrd),
                quote!(Ord),
                quote!(AsRef),
                quote!(Deref),
                quote!(TryFrom),
                quote!(Into),
                quote!(Display),
            ]);
        }
        Validation::Number { .. } => {
            derives.extend([
                quote!(Copy),
                quote!(PartialEq),
                quote!(PartialOrd),
                quote!(AsRef),
                quote!(Deref),
                quote!(TryFrom),
                quote!(Into),
                quote!(Display),
            ]);
        }
        Validation::Array { .. } => {
            derives.extend([
                quote!(PartialEq),
                quote!(AsRef),
                quote!(Deref),
                quote!(TryFrom),
                quote!(Into),
            ]);
        }
    }

    derives
}

fn integer_limit_validator(
    exclusive_name: &str,
    inclusive_name: &str,
    limit: IntegerLimit,
) -> TokenStream {
    let name = ident(if limit.exclusive {
        exclusive_name
    } else {
        inclusive_name
    });
    let value = Literal::i128_unsuffixed(limit.value);
    quote!(#name = #value)
}

fn float_limit_validator(
    exclusive_name: &str,
    inclusive_name: &str,
    limit: FloatLimit,
) -> TokenStream {
    let name = ident(if limit.exclusive {
        exclusive_name
    } else {
        inclusive_name
    });
    let value = Literal::f64_unsuffixed(limit.value);
    quote!(#name = #value)
}

fn array_predicate(min_items: Option<u64>, max_items: Option<u64>) -> TokenStream {
    match (min_items, max_items) {
        (Some(min_items), Some(max_items)) => {
            let min_items = Literal::u64_unsuffixed(min_items);
            let max_items = Literal::u64_unsuffixed(max_items);
            quote!(predicate = |items| items.len() >= #min_items && items.len() <= #max_items)
        }
        (Some(min_items), None) => {
            let min_items = Literal::u64_unsuffixed(min_items);
            quote!(predicate = |items| items.len() >= #min_items)
        }
        (None, Some(max_items)) => {
            let max_items = Literal::u64_unsuffixed(max_items);
            quote!(predicate = |items| items.len() <= #max_items)
        }
        (None, None) => unreachable!("array validation requires at least one bound"),
    }
}

fn render_struct(name: &str, fields: &[Field], serde: bool) -> syn::ItemStruct {
    let name = ident(name);
    let attrs = struct_attrs(serde);
    let fields = fields
        .iter()
        .map(|field| render_struct_field(field, serde))
        .collect::<Vec<_>>();

    parse_quote!(
        #(#attrs)*
        pub struct #name {
            #(#fields),*
        }
    )
}

fn struct_attrs(serde: bool) -> Vec<syn::Attribute> {
    let mut attrs = vec![parse_quote!(#[derive(Debug, Clone, PartialEq)])];
    if serde {
        attrs.push(parse_quote!(
            #[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
        ));
    }
    attrs
}

fn render_struct_field(field: &Field, serde: bool) -> syn::Field {
    let name = ident(&field.rust_name);
    let ty = rust_field_type(&field.ty, field.required);
    let attrs = field_attrs(field, serde);

    parse_quote!(#(#attrs)* pub #name: #ty)
}

fn field_attrs(field: &Field, serde: bool) -> Vec<syn::Attribute> {
    if !serde {
        return vec![];
    }

    let mut serde_attrs = Vec::new();
    if field.rust_name != field.wire_name {
        let wire_name = lit_str(&field.wire_name);
        serde_attrs.push(quote!(rename = #wire_name));
    }
    if !field.required {
        serde_attrs.push(quote!(default));
        serde_attrs.push(quote!(skip_serializing_if = "Option::is_none"));
    }
    if serde_attrs.is_empty() {
        vec![]
    } else {
        vec![parse_quote!(#[cfg_attr(feature = "serde", serde(#(#serde_attrs),*))])]
    }
}

fn render_enum(name: &str, variants: &[EnumVariant]) -> Vec<syn::Item> {
    let name = ident(name);
    let variant_defs = variants.iter().map(render_enum_variant).collect::<Vec<_>>();
    let as_str_arms = variants
        .iter()
        .map(render_enum_as_str_arm)
        .collect::<Vec<_>>();

    let enum_item = parse_quote!(
        #[derive(Debug, Clone, PartialEq, Eq, Default)]
        #[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
        pub enum #name {
            #(#variant_defs),*,
            #[default]
            #[cfg_attr(feature = "serde", serde(other))]
            Unknown,
        }
    );
    let inherent_impl = parse_quote!(
        impl #name {
            pub const fn as_str(&self) -> &'static str {
                match self {
                    #(#as_str_arms)*
                    Self::Unknown => "",
                }
            }
        }
    );
    let as_ref_impl = parse_quote!(
        impl AsRef<str> for #name {
            fn as_ref(&self) -> &str {
                self.as_str()
            }
        }
    );
    let display_impl = parse_quote!(
        impl std::fmt::Display for #name {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                f.write_str(self.as_str())
            }
        }
    );

    vec![enum_item, inherent_impl, as_ref_impl, display_impl]
}

fn render_enum_variant(variant: &EnumVariant) -> syn::Variant {
    let name = ident(&variant.rust_name);
    if variant.rust_name == variant.wire_name {
        parse_quote!(#name)
    } else {
        let wire_name = lit_str(&variant.wire_name);
        parse_quote!(#[cfg_attr(feature = "serde", serde(rename = #wire_name))] #name)
    }
}

fn render_enum_as_str_arm(variant: &EnumVariant) -> syn::Arm {
    let name = ident(&variant.rust_name);
    let wire_name = lit_str(&variant.wire_name);
    parse_quote!(Self::#name => #wire_name,)
}

fn render_input(operation: &Operation) -> syn::ItemStruct {
    let mut input_fields = Vec::with_capacity(
        operation.parameters.len() + usize::from(operation.request_body.is_some()),
    );
    input_fields.extend(operation.parameters.iter().map(|parameter| Field {
        wire_name: parameter.wire_name.clone(),
        rust_name: parameter.rust_name.clone(),
        ty: parameter.ty.clone(),
        required: parameter.required,
    }));
    if let Some(body) = &operation.request_body {
        input_fields.push(Field {
            wire_name: body.field_name.clone(),
            rust_name: body.field_name.clone(),
            ty: body.ty.clone(),
            required: body.required,
        });
    }

    render_struct(&operation.input_name, &input_fields, false)
}

fn render_response(operation: &Operation) -> syn::ItemEnum {
    let name = ident(&operation.response_name);
    let mut variants = operation
        .responses
        .iter()
        .map(render_response_variant)
        .collect::<Vec<_>>();
    variants.push(parse_quote!(UnexpectedStatus(http::StatusCode, Vec<u8>)));

    parse_quote!(
        #[derive(Debug, Clone, PartialEq)]
        pub enum #name {
            #(#variants),*
        }
    )
}

fn render_response_variant(response: &ResponseCase) -> syn::Variant {
    let name = ident(&response.variant_name);
    match &response.body {
        Some(body) => {
            let body = rust_type(body);
            parse_quote!(#name(#body))
        }
        None => parse_quote!(#name),
    }
}

fn render_parts_function(operation: &Operation) -> syn::ItemFn {
    let body_type = operation.request_body.as_ref().map_or_else(
        || parse_quote!(()),
        |body| rust_field_type(&body.ty, body.required),
    );
    let parts_fn = ident(&format!("{}_parts", operation.fn_name));
    let input_name = ident(if operation_uses_input(operation) {
        "input"
    } else {
        "_input"
    });
    let input_type = ident(&operation.input_name);
    let path_capacity = Literal::usize_unsuffixed(operation.path.len());

    let mut statements = vec![parse_quote!(let mut uri = String::with_capacity(#path_capacity);)];
    statements.extend(render_path(operation));
    statements.extend(render_query(operation));
    statements.extend(render_header_statements(operation));
    let request_parts = render_request_parts_return(operation);

    parse_quote!(
        pub fn #parts_fn(
            #input_name: #input_type,
        ) -> Result<satay_runtime::RequestParts<#body_type>, satay_runtime::Error> {
            #(#statements)*
            #request_parts
        }
    )
}

fn render_header_statements(operation: &Operation) -> Vec<syn::Stmt> {
    let header_parameters = operation
        .parameters
        .iter()
        .filter(|parameter| parameter.location == ParameterLocation::Header)
        .collect::<Vec<_>>();
    let needs_mutable = operation.request_body.is_some() || !header_parameters.is_empty();

    let mut statements = if needs_mutable {
        vec![parse_quote!(let mut headers = http::HeaderMap::new();)]
    } else {
        return vec![parse_quote!(let headers = http::HeaderMap::new();)];
    };

    if let Some(body) = &operation.request_body {
        let content_type = lit_str(&body.content_type);
        let insert: syn::Stmt = parse_quote!(
            headers.insert(
                http::header::CONTENT_TYPE,
                http::HeaderValue::from_static(#content_type),
            );
        );
        if body.required {
            statements.push(insert);
        } else {
            let field = ident(&body.field_name);
            statements.push(parse_quote!(
                if input.#field.is_some() {
                    #insert
                }
            ));
        }
    }

    for parameter in header_parameters {
        let wire_name = lit_str(&parameter.wire_name);
        let field = ident(&parameter.rust_name);
        let expr = value_expr(input_field(&parameter.rust_name), &parameter.ty);
        if parameter.required {
            statements.push(parse_quote!(
                satay_runtime::insert_header(&mut headers, #wire_name, #expr)?;
            ));
        } else {
            let expr = value_expr(parse_quote!(value), &parameter.ty);
            statements.push(parse_quote!(
                if let Some(value) = &input.#field {
                    satay_runtime::insert_header(&mut headers, #wire_name, #expr)?;
                }
            ));
        }
    }

    statements
}

fn render_request_parts_return(operation: &Operation) -> syn::Expr {
    let method = ident(operation.method.rust_const());
    let body = match &operation.request_body {
        Some(body) => {
            let field = ident(&body.field_name);
            quote!(input.#field)
        }
        None => quote!(()),
    };

    parse_quote!(
        Ok(satay_runtime::RequestParts {
            method: http::Method::#method,
            uri,
            headers,
            body: #body,
        })
    )
}

fn render_path(operation: &Operation) -> Vec<syn::Stmt> {
    let mut statements = Vec::new();
    for segment in &operation.path_segments {
        match segment {
            PathSegment::Literal(literal) if !literal.is_empty() => {
                let literal = lit_str(literal);
                statements.push(parse_quote!(uri.push_str(#literal);));
            }
            PathSegment::Literal(_) => {}
            PathSegment::Parameter(name) => {
                let parameter = operation
                    .parameters
                    .iter()
                    .find(|parameter| {
                        parameter.location == ParameterLocation::Path
                            && parameter.wire_name == *name
                    })
                    .expect("path parameters validated before render");
                let expr = value_expr(input_field(&parameter.rust_name), &parameter.ty);
                statements.push(parse_quote!(
                    satay_runtime::append_path_segment(&mut uri, #expr);
                ));
            }
        }
    }
    statements
}

fn render_query(operation: &Operation) -> Vec<syn::Stmt> {
    let query_parameters = operation
        .parameters
        .iter()
        .filter(|parameter| parameter.location == ParameterLocation::Query)
        .collect::<Vec<_>>();
    if query_parameters.is_empty() {
        return vec![];
    }

    let mut statements = vec![parse_quote!(let mut first_query = true;)];
    for parameter in query_parameters {
        statements.extend(render_query_parameter(parameter));
    }
    statements
}

fn render_query_parameter(parameter: &Parameter) -> Vec<syn::Stmt> {
    if let Some(item) = array_item_type(parameter.ty.non_nullable()) {
        return render_array_query_parameter(parameter, item);
    }

    let wire_name = lit_str(&parameter.wire_name);
    if parameter.required {
        let expr = value_expr(input_field(&parameter.rust_name), &parameter.ty);
        vec![parse_quote!(
            satay_runtime::append_query_pair(&mut uri, &mut first_query, #wire_name, #expr);
        )]
    } else {
        let field = ident(&parameter.rust_name);
        let expr = value_expr(parse_quote!(value), &parameter.ty);
        vec![parse_quote!(
            if let Some(value) = &input.#field {
                satay_runtime::append_query_pair(&mut uri, &mut first_query, #wire_name, #expr);
            }
        )]
    }
}

fn render_array_query_parameter(parameter: &Parameter, item: &TypeRef) -> Vec<syn::Stmt> {
    let wire_name = lit_str(&parameter.wire_name);
    let value = value_expr(parse_quote!(value), item);

    if parameter.required {
        let values = array_values_expr(
            input_field(&parameter.rust_name),
            &parameter.ty,
            ArrayValueBase::Owned,
        );
        vec![parse_quote!(
            for value in #values {
                satay_runtime::append_query_pair(&mut uri, &mut first_query, #wire_name, #value);
            }
        )]
    } else {
        let field = ident(&parameter.rust_name);
        let values = array_values_expr(
            parse_quote!(values),
            &parameter.ty,
            ArrayValueBase::Borrowed,
        );
        vec![parse_quote!(
            if let Some(values) = &input.#field {
                for value in #values {
                    satay_runtime::append_query_pair(&mut uri, &mut first_query, #wire_name, #value);
                }
            }
        )]
    }
}

fn array_item_type(ty: &TypeRef) -> Option<&TypeRef> {
    match ty {
        TypeRef::Array(item) => Some(item),
        TypeRef::Constrained { inner, .. } => array_item_type(inner.non_nullable()),
        _ => None,
    }
}

#[derive(Clone, Copy)]
enum ArrayValueBase {
    Owned,
    Borrowed,
}

fn array_values_expr(base: syn::Expr, ty: &TypeRef, base_kind: ArrayValueBase) -> syn::Expr {
    match ty.non_nullable() {
        TypeRef::Array(_) => match base_kind {
            ArrayValueBase::Owned => parse_quote!(&#base),
            ArrayValueBase::Borrowed => base,
        },
        TypeRef::Constrained { inner, .. } if is_array_type(inner.non_nullable()) => {
            parse_quote!(#base.as_ref())
        }
        _ => unreachable!("array values are only rendered for array types"),
    }
}

fn render_encode_function(operation: &Operation) -> syn::ItemFn {
    let parts_fn = ident(&format!("{}_parts", operation.fn_name));
    let encode_fn = ident(&format!("encode_{}", operation.fn_name));
    let input_type = ident(&operation.input_name);
    let encode_expr: syn::Expr = match &operation.request_body {
        Some(body) if body.required => parse_quote!(satay_runtime::into_json_request(parts)),
        Some(_) => parse_quote!(satay_runtime::into_optional_json_request(parts)),
        None => parse_quote!(satay_runtime::into_empty_request(parts)),
    };

    parse_quote!(
        pub fn #encode_fn(input: #input_type) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
            let parts = #parts_fn(input)?;
            #encode_expr
        }
    )
}

fn render_decode_function(operation: &Operation) -> syn::ItemFn {
    let decode_fn = ident(&format!("decode_{}_response", operation.fn_name));
    let response_name = ident(&operation.response_name);
    let arms = operation
        .responses
        .iter()
        .map(|response| render_decode_arm(response, &response_name))
        .collect::<Vec<_>>();

    parse_quote!(
        pub fn #decode_fn(
            response: http::Response<Vec<u8>>,
        ) -> Result<#response_name, satay_runtime::Error> {
            let status = response.status();
            match status.as_u16() {
                #(#arms)*
                _ => {
                    let body = response.into_body();
                    Ok(#response_name::UnexpectedStatus(status, body))
                }
            }
        }
    )
}

fn render_decode_arm(response: &ResponseCase, response_name: &Ident) -> syn::Arm {
    let status = Literal::u16_unsuffixed(response.status);
    let variant = ident(&response.variant_name);
    match &response.body {
        Some(body) => {
            let body = rust_type(body);
            parse_quote!(
                #status => {
                    let body = response.into_body();
                    let value = satay_runtime::from_json_slice::<#body>(&body)?;
                    Ok(#response_name::#variant(value))
                }
            )
        }
        None => parse_quote!(
            #status => {
                Ok(#response_name::#variant)
            }
        ),
    }
}

fn operation_uses_input(operation: &Operation) -> bool {
    !operation.parameters.is_empty() || operation.request_body.is_some()
}

fn value_expr(base: syn::Expr, ty: &TypeRef) -> syn::Expr {
    match ty.non_nullable() {
        TypeRef::String => parse_quote!(#base.as_str()),
        TypeRef::Named(_) => parse_quote!(#base.as_ref()),
        TypeRef::Constrained { inner, .. } => constrained_value_expr(base, inner.non_nullable()),
        TypeRef::I32 | TypeRef::I64 | TypeRef::F32 | TypeRef::F64 | TypeRef::Bool => {
            parse_quote!(&#base.to_string())
        }
        TypeRef::Array(_) | TypeRef::Nullable(_) => unreachable!("arrays are handled by caller"),
    }
}

fn constrained_value_expr(base: syn::Expr, inner: &TypeRef) -> syn::Expr {
    match inner {
        TypeRef::String | TypeRef::Named(_) => parse_quote!(#base.as_ref()),
        TypeRef::I32 | TypeRef::I64 | TypeRef::F32 | TypeRef::F64 | TypeRef::Bool => {
            parse_quote!(&#base.to_string())
        }
        TypeRef::Array(_) | TypeRef::Constrained { .. } | TypeRef::Nullable(_) => {
            unreachable!("arrays are handled by caller")
        }
    }
}

fn rust_type(ty: &TypeRef) -> syn::Type {
    match ty {
        TypeRef::String => parse_quote!(String),
        TypeRef::I32 => parse_quote!(i32),
        TypeRef::I64 => parse_quote!(i64),
        TypeRef::F32 => parse_quote!(f32),
        TypeRef::F64 => parse_quote!(f64),
        TypeRef::Bool => parse_quote!(bool),
        TypeRef::Array(item) => {
            let item = rust_type(item);
            parse_quote!(Vec<#item>)
        }
        TypeRef::Named(name)
        | TypeRef::Constrained {
            rust_name: name, ..
        } => {
            let name = ident(name);
            parse_quote!(#name)
        }
        TypeRef::Nullable(inner) => {
            let inner = rust_type(inner);
            parse_quote!(Option<#inner>)
        }
    }
}

fn rust_field_type(ty: &TypeRef, required: bool) -> syn::Type {
    if required || ty.is_nullable() {
        rust_type(ty)
    } else {
        let ty = rust_type(ty);
        parse_quote!(Option<#ty>)
    }
}

fn input_field(field: &str) -> syn::Expr {
    let field = ident(field);
    parse_quote!(input.#field)
}

fn ident(value: &str) -> Ident {
    Ident::new(value, Span::call_site())
}

fn lit_str(value: &str) -> LitStr {
    LitStr::new(value, Span::call_site())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::{HttpMethod, RequestBody};
    use syn::{Expr, Fields, GenericArgument, PathArguments, Stmt, Type};

    #[test]
    fn add_blank_lines_between_items_inserts_line_after_closing_brace() {
        let input = "pub struct Foo {\n    x: i32,\n}\npub struct Bar {\n    y: i32,\n}\n";
        let result = add_blank_lines_between_items(input);
        assert_eq!(
            result,
            "pub struct Foo {\n    x: i32,\n}\n\npub struct Bar {\n    y: i32,\n}\n"
        );
    }

    #[test]
    fn add_blank_lines_between_items_inserts_line_before_impl() {
        let input = "pub struct Foo {\n    x: i32,\n}\nimpl Foo {\n    fn bar() {}\n}\n";
        let result = add_blank_lines_between_items(input);
        assert_eq!(
            result,
            "pub struct Foo {\n    x: i32,\n}\n\nimpl Foo {\n    fn bar() {}\n}\n"
        );
    }

    #[test]
    fn add_blank_lines_between_items_inserts_line_before_attribute() {
        let input = "pub struct Foo {\n    x: i32,\n}\n#[derive(Clone)]\npub struct Bar {\n    y: i32,\n}\n";
        let result = add_blank_lines_between_items(input);
        assert_eq!(
            result,
            "pub struct Foo {\n    x: i32,\n}\n\n#[derive(Clone)]\npub struct Bar {\n    y: i32,\n}\n"
        );
    }

    #[test]
    fn add_blank_lines_between_items_does_not_insert_inside_function() {
        let input = "pub fn foo() {\n    if true {}\n    let x = 1;\n}\n";
        let result = add_blank_lines_between_items(input);
        assert_eq!(result, input);
    }

    #[test]
    fn render_file_exposes_struct_ast_without_source_comparison() {
        let api = Api {
            components: vec![Component {
                rust_name: "Pet".to_owned(),
                kind: ComponentKind::Struct(vec![
                    Field {
                        wire_name: "id".to_owned(),
                        rust_name: "id".to_owned(),
                        ty: TypeRef::String,
                        required: true,
                    },
                    Field {
                        wire_name: "tag_count".to_owned(),
                        rust_name: "tag_count".to_owned(),
                        ty: TypeRef::I32,
                        required: false,
                    },
                ]),
            }],
            constrained_types: vec![],
            operations: vec![],
        };

        let file = render_types_file(&api);
        assert_eq!(file.items.len(), 1);
        let Item::Struct(item) = &file.items[0] else {
            panic!("expected struct item");
        };
        assert_eq!(item.ident, "Pet");
        let Fields::Named(fields) = &item.fields else {
            panic!("expected named fields");
        };
        assert_eq!(fields.named.len(), 2);

        let mut fields = fields.named.iter();
        let id = fields.next().expect("id field");
        assert_eq!(id.ident.as_ref().expect("field ident"), "id");
        assert!(type_path_is(&id.ty, "String"));

        let tag_count = fields.next().expect("tag_count field");
        assert_eq!(tag_count.ident.as_ref().expect("field ident"), "tag_count");
        let Some(inner) = option_inner(&tag_count.ty) else {
            panic!("optional field should render as Option<T>");
        };
        assert!(type_path_is(inner, "i32"));
    }

    #[test]
    fn render_file_exposes_operation_items_without_source_comparison() {
        let api = Api {
            components: vec![],
            constrained_types: vec![],
            operations: vec![Operation {
                fn_name: "create_pet".to_owned(),
                input_name: "CreatePetInput".to_owned(),
                response_name: "CreatePetResponse".to_owned(),
                method: HttpMethod::Post,
                path: "/pets".to_owned(),
                path_segments: vec![PathSegment::Literal("/pets".to_owned())],
                parameters: vec![],
                request_body: Some(RequestBody {
                    field_name: "body".to_owned(),
                    content_type: "application/json".to_owned(),
                    ty: TypeRef::Named("Pet".to_owned()),
                    required: true,
                }),
                responses: vec![ResponseCase {
                    status: 201,
                    variant_name: "Created".to_owned(),
                    body: Some(TypeRef::Named("Pet".to_owned())),
                }],
            }],
        };

        let files = render_api(&api);
        assert!(files.iter().any(|f| f.relative_path == "mod.rs"));
        assert!(files.iter().any(|f| f.relative_path == "create_pet/mod.rs"));
        assert!(files.iter().any(|f| f.relative_path == "create_pet/parts.rs"));
        assert!(files.iter().any(|f| f.relative_path == "create_pet/json.rs"));
    }

    #[test]
    fn optional_plain_array_query_iterates_borrowed_binding() {
        let operation = Operation {
            fn_name: "list_pets".to_owned(),
            input_name: "ListPetsInput".to_owned(),
            response_name: "ListPetsResponse".to_owned(),
            method: HttpMethod::Get,
            path: "/pets".to_owned(),
            path_segments: vec![PathSegment::Literal("/pets".to_owned())],
            parameters: vec![Parameter {
                location: ParameterLocation::Query,
                wire_name: "tags".to_owned(),
                rust_name: "tags".to_owned(),
                ty: TypeRef::Array(Box::new(TypeRef::String)),
                required: false,
            }],
            request_body: None,
            responses: vec![ResponseCase {
                status: 204,
                variant_name: "NoContent".to_owned(),
                body: None,
            }],
        };

        let parts = render_parts_function(&operation);
        let if_expr = parts
            .block
            .stmts
            .iter()
            .find_map(|stmt| match stmt {
                Stmt::Expr(Expr::If(if_expr), _) => Some(if_expr),
                _ => None,
            })
            .expect("optional query guard");
        let Stmt::Expr(Expr::ForLoop(for_loop), _) = &if_expr.then_branch.stmts[0] else {
            panic!("optional array query should render a for loop");
        };
        assert!(expr_path_is(&for_loop.expr, "values"));
    }

    fn type_path_is(ty: &syn::Type, expected: &str) -> bool {
        let Type::Path(path) = ty else {
            return false;
        };
        path.path.is_ident(expected)
    }

    fn expr_path_is(expr: &syn::Expr, expected: &str) -> bool {
        let Expr::Path(path) = expr else {
            return false;
        };
        path.path.is_ident(expected)
    }

    fn option_inner(ty: &syn::Type) -> Option<&syn::Type> {
        let Type::Path(path) = ty else {
            return None;
        };
        let segment = path.path.segments.first()?;
        if segment.ident != "Option" {
            return None;
        }
        let PathArguments::AngleBracketed(arguments) = &segment.arguments else {
            return None;
        };
        let GenericArgument::Type(inner) = arguments.args.first()? else {
            return None;
        };
        Some(inner)
    }
}